name: Release with Signing and Changelog
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This ensures we get the full history for changelog generation
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build React app
        run: npm run react-build
        env:
          CI: false
          
      - name: Build and Sign Windows App
        run: npm run electron-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Changelog
        id: changelog
        run: |
          # Extract the version from the tag
          $VERSION=${env:GITHUB_REF_NAME} -replace '^v',''
          
          # Read CHANGELOG.md and extract the section for this version
          $CHANGELOG = Get-Content -Path CHANGELOG.md -Raw
          if ($CHANGELOG -match "(?ms)## \[\s*$VERSION\s*\].*?(?=## \[|$)") {
            $CHANGELOG_SECTION = $Matches[0].Trim()
            $CHANGELOG_SECTION | Out-File -FilePath changelog_section.txt -Encoding utf8
            echo "::set-output name=exists::true"
          } else {
            echo "No changelog entry found for version $VERSION"
            echo "::set-output name=exists::false"
          }
        shell: pwsh
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*.exe"
          draft: false
          prerelease: false
          body_path: ${{ steps.changelog.outputs.exists == 'true' && 'changelog_section.txt' || '' }}
          generate_release_notes: ${{ steps.changelog.outputs.exists != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}